### ISSUE TITLE
Downloading .exe causes crash

### ISSUE THREAD

**Issue by DeerSpotter** [KerryL/Converter#3]
I had to download the full source folder so it wouldnt crash. Why offer just the .exe for download if it doesnt work on its own?

**Comment by KerryL** [comment]
I'm assuming that you don't actually mean that the application crashes, but that the application generates a message telling you that the conversions file is missing, then it exits. Is this correct?

You don't need to download the whole source, but you do need the conversions.xml file. That file is included in the downloaded assets for each release.

**Comment by Drayak335** [comment]
@KerryL  you are correct it throw an error stating 

> "can't open file 'conversions.xml' (error 2: the system cannot find the file specified.).

When you hit OK application still displayed, but everything blank and crashes when you click on any button.
![image](https://user-images.githubusercontent.com/12659538/162472502-4fdf68f0-0c9f-4709-9422-91331c1abc73.png)

Would it be possible to autogenerate the initial xml file if one is not found?

**Comment by KerryL** [comment]
Yep, you're correct. I'll fix the crash issue.

I'll modify the application so if you don't have a conversions.xml file you'll be able to create one using the Options button, but I don't think the effort required to automatically generate a relatively complete default file is worth it. For future releases, I'll try to make it more clear that you need to download both the executable and the conversions.xml file.
